sudo: false
language: node_js
node_js:
  - 8

cache:
  directories:
  - node_modules

install: npm i

branches:
  only:
  - master

before_deploy: npm run build-storybook

deploy:
  - provider: surge
    project: ./storybook-static
    domain: styleguide.moberries.com
    skip_cleanup: true
    on:
      branch: master
